version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: avinci-postgres
    environment:
      POSTGRES_DB: avinci
      POSTGRES_USER: avinci_user
      POSTGRES_PASSWORD: avinci_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - avinci-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: avinci-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - avinci-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: avinci-backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://avinci_user:avinci_password@postgres:5432/avinci
      - REDIS_URL=redis://redis:6379
      - PORT=9001
    ports:
      - "9001:9001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - avinci-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: avinci-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:9001/api
      - PORT=9000
    ports:
      - "9000:9000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - avinci-network

  # Data Processing Service
  data-processing:
    build:
      context: ./data-processing
      dockerfile: Dockerfile
    container_name: avinci-data-processing
    environment:
      - DATABASE_URL=postgresql://avinci_user:avinci_password@postgres:5432/avinci
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data-processing:/app
    networks:
      - avinci-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: avinci-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - avinci-network

volumes:
  postgres_data:
  redis_data:

networks:
  avinci-network:
    driver: bridge
